<!DOCTYPE html>
<!-- Desarrollo Web en Entorno Servidor -->
<!-- Tema 3: Desarrollo de aplicaciones web en PHP -->
<!-- Felipe Rodríguez Gutiérrez -->
<!-- Tarea: 03 Foro DWES -->
<html>
    
<head>
    <meta charset="UTF-8">
    <title>DWES - Tarea 3 - Felipe Rodríguez Gutiérrez</title>
    <link type="text/css" href="css/<?php echo theme();?>.css" rel="stylesheet" />
</head>

<body>
    
    <h1 class="centrado">TAREA 3: FORO DWES</h1>
    <h2 class="centrado">Felipe Rodríguez Gutiérrez</h2>